import { PDFTool } from './types';

export const TOOLS: PDFTool[] = [
  {
    id: 'merge',
    name: 'Merge PDF',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    icon: 'Combine',
    category: 'organize',
    href: '/merge-pdf',
    color: 'bg-red-500',
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF quality.',
    icon: 'FileArchive',
    category: 'optimize',
    href: '/compress-pdf',
    color: 'bg-green-500',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Extract all images that are within a PDF file or convert each page to a JPG image.',
    icon: 'Image',
    category: 'convert',
    href: '/pdf-to-jpg',
    color: 'bg-yellow-500',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG, PNG, BMP, GIF and TIFF images to PDF in seconds.',
    icon: 'FileImage',
    category: 'convert',
    href: '/jpg-to-pdf',
    color: 'bg-yellow-600',
  },
  {
    id: 'edit',
    name: 'Edit PDF',
    description: 'Add text, images, shapes or freehand annotations to a PDF document.',
    icon: 'Edit3',
    category: 'edit',
    href: '/edit-pdf',
    color: 'bg-purple-500',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert your PDF files into editable DOCX documents with text extraction.',
    icon: 'FileType',
    category: 'convert',
    href: '/pdf-to-word',
    color: 'bg-blue-500',
  },
  {
    id: 'watermark',
    name: 'Watermark',
    description: 'Add text over your PDF with transparency and positioning.',
    icon: 'Type',
    category: 'edit',
    href: '/watermark-pdf',
    color: 'bg-blue-400',
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate your PDF pages precisely as you want them to be.',
    icon: 'RotateCw',
    category: 'organize',
    href: '/rotate-pdf',
    color: 'bg-rose-400',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Easily add page numbers to your PDF document at custom positions.',
    icon: 'Hash',
    category: 'edit',
    href: '/page-numbers-pdf',
    color: 'bg-indigo-400',
  },
];
